language: ruby
cache: bundler
rvm:
  - 2.0.0
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
script:
  - RAILS_ENV=test bundle exec rake db:drop db:create db:migrate
  - bundle exec rspec spec/
