language: ruby
cache: bundler
addons:
  postgresql: "9.3"
rvm:
  - 2.0.0
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec spec/
  - npm run-script test-single-run-ci
